---
- name: Install k3s server service
  get_url:
    url: https://raw.githubusercontent.com/rancher/k3s/master/k3s.service
    dest: /etc/systemd/system/k3s-server.service
    mode: a+x
    force: yes

- name: Start the k3s service
  debug:
    msg: "Starting "
  notify: start k3s


# not sure why I can't get the values from the previous task
- name: Set server address
  set_fact:
    k3s_server_address: "https://{{ ansible_facts.eth0.ipv4.address }}:6443"
  register: k3s_server_address
  run_once: yes

- name: Print server address ( server )
  debug:
    msg: "{{ k3s_server_address }}"
