---
- name: Install k3s server service
  get_url:
    url: https://raw.githubusercontent.com/lcwyo/ansible-k3s-rpi/master/ansible/roles/k3s-server/k3s.service
    dest: /etc/systemd/system/k3s-server.service
    mode: a+x
    force: yes

- name: Enable and start the k3s server service
  service:
    name: k3s-server
    enabled: yes
    state: started
