---
- name: Install k3s server service
  get_url:
<<<<<<< HEAD
    url: https://raw.githubusercontent.com/rancher/k3s/master/k3s.service
=======
    url: https://raw.githubusercontent.com/lcwyo/ansible-k3s-rpi/master/ansible/roles/k3s-server/tasks/k3s.service
>>>>>>> c096e3ecd02142bcdabd99998b2d25ccde988b06
    dest: /etc/systemd/system/k3s-server.service
    mode: a+x
    force: yes

- name: Enable and start the k3s server service
  service:
    name: k3s-server
    enabled: yes
    state: started
