---
- name: Ensure US locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set hostname to inventory hostname
  hostname: name={{inventory_hostname}}

- name: Update apt cache
  shell: apt update

- name: Remove useless packages from the cache
  shell: apt autoclean

- name: Remove dependencies that are no longer required
  shell: apt autoremove -y
