#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "please provide the playbook to run"
    echo "for example: "
    echo "`basename "$0"` /ansible/site.yml -i /ansible/hosts"
    exit 1
fi




docker run --rm -it \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v $(pwd):/ansible/ \
  lcwyo/ansible-player "$@"
