---
- name: Set up Raspberry pi for k3s
  hosts: all
  remote_user: pi
  become: yes
  become_user: root

  roles:
#    - raspi-config
    - common


- name: Provision k3s nodes
  hosts: server:agents
  remote_user: pi
  become: yes
  become_user: root

  roles:
    - { role: k3s-common }

- name: Provision k3s server node
  hosts: server
  remote_user: pi
  become: yes
  become_user: root


  roles:
    - { role: k3s-server }



- name: Get k3s server config for all nodes
  hosts: server
  remote_user: pi
  become: yes
  become_user: root

  roles:
    - { role: k3s-config }


- name: Provision k3s agent nodes
  hosts: agents
  remote_user: pi
  become: yes
  become_user: root

  roles:
    - { role: k3s-agent }
